### ISSUE TITLE
Can not run dbt-profiler interactively in dbt-cloud

### ISSUE THREAD

**Issue by ernestoongaro** [data-mie/dbt-profiler#30]
expecting to be able to run is similar to codegen:
`{{ codegen.generate_model_yaml('dim_customers') }}`
which when hitting </> Compile, yields an output
but when using 
`{{ dbt_profiler.print_profile('dim_customers') }}`
I get 
> Relation “dim_customers” does not exist or not authorized.)

Slack 🧵  [here](https://getdbt.slack.com/archives/CMZ2V0X8V/p1637821438253300?thread_ts=1637776895.250000&cid=CMZ2V0X8V)

**Comment by ernestoongaro** [comment]
Tried setting the relation like `{% set relation=ref(relation_name) %}` got me closer, but no luck. Something is definitely different about directly invoking vs run_operation

**Comment by stumelius** [comment]
@ernestoongaro Did you manage to get past the "does not exist or not authorized" error?

**Comment by ernestoongaro** [comment]
I did by replacing (in get_profile.sql)

```
{%- 
set relation = adapter.get_relation(
  database=database,
  schema=schema,
  identifier=relation_name
) 
-%}
```

with ```{% set relation=ref(relation_name) %}``` however after that I was still seeing other errors which pointed to my limited knowledge of how this all works

**Comment by stumelius** [comment]
@ernestoongaro I made some changes and now the [get_profile](https://github.com/data-mie/dbt-profiler#get_profile-source) macro should work in dbt Cloud. Example usage:

```sql
{{ dbt_profiler.get_profile(relation=ref("customers")) }}
```

Can you verify if this now works for you?

**Comment by ernestoongaro** [comment]
This is working really well - tried a few relations and it looks 💯  Thank you!!!

Fixed by @stumelius in https://github.com/data-mie/dbt-profiler/pull/31
