### ISSUE TITLE
CTE Query Optimization

### ISSUE THREAD

**Issue by belaidcherfa** [data-mie/dbt-profiler#45]
Hello,
I use your package for profiling and I find it great ! Thank's for your contribution.
I use Snwoflake for the compute part and I noticed (tested) a potential optimization
What is currently being done
A "column_profiles" CTE that performs a union all for each column and reads from the source table (DB.SCHEMA.TABLE) .

When analyzing the snowflake profile query, it performs as many table scans as there are columns. for large volumes, the small warehouse is not enough and returns a memory error.

We can optimize a little by adding a first cte to read the source table in full and then reference this cte for each column, that will force snowflake to read the table only once, mount it in memory and then use it.

I have metrics, we divide by 3/4 the amount of I/O , There is also the number of partitions, In my case 

Before
![2022-05-17_13h21_54](https://user-images.githubusercontent.com/17992648/168799890-629e5dd1-e8de-4f9b-bcaf-1c2dc6aac2f3.png)

After
![2022-05-17_13h11_07](https://user-images.githubusercontent.com/17992648/168799934-0c338f9c-1ea8-4f89-8e5f-7e0b188a8ee5.png)

PS : The notion of cache in the original runtime doesn't matter since I disabled the session cache
ALTER SESSION SET USE_CACHED_RESULT = FALSE;
I also restarted the warehouses between each execution (using several warehouses on different time intervals). I can't explain myself but I think it's a common cache due to union all.
On the execution times, there is not a big difference but I have tests on large tables where the first query does not succeed because of the number of columns (1000) and the size of the table
I remain at your disposal in case of more information

Snippet code 
![2022-05-17_13h35_23](https://user-images.githubusercontent.com/17992648/168801901-07391f3b-a3e0-43b1-857a-d80415a4ad88.png)

**Comment by stumelius** [comment]
@belaidcherfa Wow, this is awesome! Thanks for all the work you've put into researching this ❤️ I have totally overlooked the performance part and I really appreciate your help.

Implementing this is straightforward. Do you want to have a crack at it and create a PR? I can also do it, no problem.

**Comment by stumelius** [comment]
I'm excited to see what other Snowflake optimizations you come up with! 💯
