### ISSUE TITLE
Question: running dbt run-operation print_profile_docs prints log info

### ISSUE THREAD

**Issue by Jaxing** [data-mie/dbt-profiler#50]
running `dbt run-operation print_profile_docs` prints the normal dbt logging information e.g. timestamps when it's run and dbt version.
Is there a way to remove this or how do I print this to file otherwise?

Example of output for me
```
12:58:59  Running with dbt=1.1.1
12:59:06  {% docs dbt_profiler__time_to_merge  %}
| column_name   | data_type | row_count | not_null_proportion | distinct_proportion | distinct_count | is_unique | min                    | max                    |                avg | std_dev_population |    std_dev_sample | profiled_at                   |
| ------------- | --------- | --------- | ------------------- | ------------------- | -------------- | --------- | ---------------------- | ---------------------- | ------------------ | ------------------ | ----------------- | ----------------------------- |
| merged_at     | timestamp |       351 |                   1 |         1,000000000 |            351 |      True | 2022-07-12 07:48:30+00 | 2022-09-13 17:09:22+00 |                    |                    |                   | 2022-09-16 12:59:05.495281+00 |
| time_to_merge | int64     |       351 |                   1 |         0,894586895 |            314 |     False | 4                      | 5523425                | 218 528,3219373218 | 595 672,7009238278 | 596 523,054962641 | 2022-09-16 12:59:05.495281+00 |
12:59:06  {% enddocs %}
```

I expected that I could use this opperation like this `dbt run-operation print_profile_docs <args> > some_file.md` however then I'll get the timestamp and other output that will break the docs reference. If I want to run this in a ci workflow then copy pasting is not an option!

Thanks for your help

**Comment by stumelius** [comment]
Hey @Jaxing ! I haven't yet found a way to get the dbt log messages excluded from the output but you can use `sed` to clean it. See this example: https://github.com/data-mie/dbt-profiler/blob/main/update-relation-profile.sh#L14. Does that work for you?

**Comment by Jaxing** [comment]
Hey, thanks for the response! Yeah it's just me not reading the documentation closely enough
