### ISSUE TITLE
Question: Are you planning to extend dbt-profiler for dbt-sqlserver adapter?

### ISSUE THREAD

**Issue by agn-sta** [data-mie/dbt-profiler#51]
Like the above: Are you planning to extend dbt-profiler for dbt-sqlserver adapter?

**Comment by stumelius** [comment]
@agn-sta There are no plans for extending the profiler compatibility to SQL Server. If you'd like to implement the feature I'm happy to help and answer any questions you have :)

**Comment by agn-sta** [comment]
Okay, thank you for a quick answer ;)
