### ISSUE TITLE
Feature request: Handling structs

### ISSUE THREAD

**Issue by eve-johns** [data-mie/dbt-profiler#67]
Currently the macro `get_profile` cannot handle struct columns. I tried using struct itself, or using struct_col.*. It would either show this below error message or missing the `column_profiles` cte in compiled code.

![image](https://user-images.githubusercontent.com/105383716/217919704-998da350-1bd7-4ea5-8f94-7b76f1420e42.png)

**Comment by stumelius** [comment]
@eve-johns Thanks for raising this issue. I implemented a fix and created a new release https://github.com/data-mie/dbt-profiler/releases/tag/0.6.3
