### ISSUE TITLE
Suggestion to modify `sed` to `awk` in update-relation-profile.sh

### ISSUE THREAD

**Issue by ian-lewis-d** [data-mie/dbt-profiler#72]
https://github.com/data-mie/dbt-profiler/blob/5c7002eaa3a8947756c223422b147b02a516bd90/update-relation-profile.sh#L14

**Current**:
`PROFILE=$(echo "$RUN_OPERATION_OUTPUT" | sed -n '/{% docs/,$p')`

**Suggested replacement**:

 PROFILE=$(echo "$RUN_OPERATION_OUTPUT" |  awk '/\{%.docs.*%\}$/{flag=1} flag; /\{%.enddocs.%\}/{flag=0}')

**Comment by stumelius** [comment]
@ian-lewis-d Thanks so much for this! I never liked the hacky sed I came up with, this looks much better :) Merged in #73
