### ISSUE TITLE
Run profiler for all models

### ISSUE THREAD

**Issue by moseleyi** [data-mie/dbt-profiler#78]
Is it possible to just include the profiler to all models and keep the output in another table with the results to have historical data?

**Comment by stumelius** [comment]
Hi @moseleyi ! Currently, there's no way to profile all models in a single macro execution. However, you can write a custom script that loops all the models and profiles them individually. Would this be sufficient for your needs? :)

**Comment by moseleyi** [comment]
I think so. Thanks for clarification @stumelius
