### ISSUE TITLE
Old version of example output, without median column

### ISSUE THREAD

**Issue by odikia** [data-mie/dbt-profiler#87]
Hi there,

In working on another issue for the dbt-profiler, I compared my results to example output in the readme, and found that the output is a little dated, as it aligns aligns with release 0.6.4, rather than >= 0.7.0.

https://github.com/data-mie/dbt-profiler/blob/c1c7850a22a00966197996fc0baed40d50cb27c1/README.md?plain=1#L50

**Comment by stumelius** [comment]
@odikia I think you're right - good catch! Would you be open (pun intended) to opening a PR for that? :)

And by the way, I really appreciate your thoughts and help in maintaining this project ❤️

**Comment by odikia** [comment]
@stumelius , Will do! :) 

Glad to do it!!

**Comment by stumelius** [comment]
Thank you for your contribution! https://github.com/data-mie/dbt-profiler/releases/tag/0.8.2
